export const EnLanguageCode = 'en';
export const EnUSLanguageCode = 'en-US';

export interface Language {
    language: string;
    languageCode: string;
}

export const Languages: Language[] = [
    { "language": "Afrikaans", "languageCode": "af" },
    { "language": "Albanian", "languageCode": "sq" },
    { "language": "Amharic", "languageCode": "am" },
    { "language": "Arabic", "languageCode": "ar" },
    { "language": "Armenian", "languageCode": "hy" },
    { "language": "Azerbaijani", "languageCode": "az" },
    { "language": "Bangla", "languageCode": "bn" },
    { "language": "Basque", "languageCode": "eu" },
    { "language": "Bosnian", "languageCode": "bs" },
    { "language": "Bulgarian", "languageCode": "bg" },
    { "language": "Burmese", "languageCode": "my" },
    { "language": "Catalan", "languageCode": "ca" },
    { "language": "Chinese", "languageCode": "cmn" },
    { "language": "Croatian", "languageCode": "hr" },
    { "language": "Czech", "languageCode": "cs" },
    { "language": "Danish", "languageCode": "da" },
    { "language": "Dutch", "languageCode": "nl" },
    { "language": "English", "languageCode": "en" },
    { "language": "Estonian", "languageCode": "et" },
    { "language": "Filipino", "languageCode": "fil" },
    { "language": "Finnish", "languageCode": "fi" },
    { "language": "French", "languageCode": "fr" },
    { "language": "Galician", "languageCode": "gl" },
    { "language": "Georgian", "languageCode": "ka" },
    { "language": "German", "languageCode": "de" },
    { "language": "Greek", "languageCode": "el" },
    { "language": "Gujarati", "languageCode": "gu" },
    { "language": "Hebrew", "languageCode": "he" },
    { "language": "Hindi", "languageCode": "hi" },
    { "language": "Hungarian", "languageCode": "hu" },
    { "language": "Icelandic", "languageCode": "is" },
    { "language": "Indonesian", "languageCode": "id" },
    { "language": "Irish", "languageCode": "ga" },
    { "language": "Italian", "languageCode": "it" },
    { "language": "Japanese", "languageCode": "ja" },
    { "language": "Javanese", "languageCode": "jv" },
    { "language": "Kannada", "languageCode": "kn" },
    { "language": "Kazakh", "languageCode": "kk" },
    { "language": "Khmer", "languageCode": "km" },
    { "language": "Korean", "languageCode": "ko" },
    { "language": "Lao", "languageCode": "lo" },
    { "language": "Latvian", "languageCode": "lv" },
    { "language": "Lithuanian", "languageCode": "lt" },
    { "language": "Malayalam", "languageCode": "ml" },
    { "language": "Malaysian", "languageCode": "ms" },
    { "language": "Maltese", "languageCode": "mt" },
    { "language": "Marathi", "languageCode": "mr" },
    { "language": "Macedonian", "languageCode": "mk" },
    { "language": "Mongolian", "languageCode": "mn" },
    { "language": "Norwegian", "languageCode": "nb" },
    { "language": "Nepali", "languageCode": "ne" },
    { "language": "Pashto", "languageCode": "ps" },
    { "language": "Persian", "languageCode": "fa" },
    { "language": "Polish", "languageCode": "pl" },
    { "language": "Portuguese", "languageCode": "pt" },
    { "language": "Punjabi", "languageCode": "pa" },
    { "language": "Romanian", "languageCode": "ro" },
    { "language": "Russian", "languageCode": "ru" },
    { "language": "Serbian", "languageCode": "sr" },
    { "language": "Slovak", "languageCode": "sk" },
    { "language": "Slovene", "languageCode": "sl" },
    { "language": "Somali", "languageCode": "so" },
    { "language": "Spanish", "languageCode": "es" },
    { "language": "Swahili", "languageCode": "sw" },
    { "language": "Swedish", "languageCode": "sv" },
    { "language": "Tamil", "languageCode": "ta" },
    { "language": "Telugu", "languageCode": "te" },
    { "language": "Thai", "languageCode": "th" },
    { "language": "Turkish", "languageCode": "tr" },
    { "language": "Ukrainian", "languageCode": "uk" },
    { "language": "Urdu", "languageCode": "ur" },
    { "language": "Uzbek", "languageCode": "uz" },
    { "language": "Vietnamese", "languageCode": "vi" },
    { "language": "Welsh", "languageCode": "cy" }
];
