services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    networks:
      - elk

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    external: true

volumes:
  test_data:
  ls_data:
  kb_data:

#todo elk delete
#openssl req -x509 -newkey rsa:4096 -keyout elk-config/ssl/key.pem -out elk-config/ssl/cert.pem -days 365
#openssl pkcs12 -export -out elk-config/ssl/keystore.p12 -inkey elk-config/ssl/key.pem -in elk-config/ssl/cert.pem
#elasticsearch-certutil cert --pem --in elk-config/ssl/keystore.p12 --out elk-config/ssl/elastic-certificates.p12
