services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - network.host=0.0.0.0
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ElasticsearchConfig__Password} 
    env_file: .env
    networks:
      - proxy_elk

  kibana:
    image: kibana:9.1.2
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - kb_data:/usr/share/kibana/data
    environment:
      - server.name=kibana
      - server.host=0.0.0.0
      - elasticsearch.hosts=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ElasticsearchConfig__Password} 
    env_file: .env
    networks:
      - proxy_elk
    depends_on:
      - elasticsearch

networks:
  proxy_elk:
    external: true
    name: elk

volumes:
  test_data:
  ls_data:
  kb_data:
