services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - network.host=0.0.0.0
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${Elasticsearch__Password} 
    env_file: .env
    networks:
      - elk_nework

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - kb_data:/usr/share/kibana/data
    environment:
      - server.name=kibana
      - server.host=0.0.0.0
      - elasticsearch.hosts=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${Elasticsearch__Password} 
    env_file: .env
    networks:
      - elk_nework
    depends_on:
      - elasticsearch

networks:
   elk_nework:
    name: elk
    driver: bridge

volumes:
  test_data:
  ls_data:
  kb_data:

#todo elk delete
#openssl req -x509 -newkey rsa:4096 -keyout elk-config/ssl/key.pem -out elk-config/ssl/cert.pem -days 365
#openssl pkcs12 -export -out elk-config/ssl/keystore.p12 -inkey elk-config/ssl/key.pem -in elk-config/ssl/cert.pem
#elasticsearch-certutil cert --pem --in elk-config/ssl/keystore.p12 --out elk-config/ssl/elastic-certificates.p12
