name: CI

on:
  push:
    branches:
      - master
      - dev
      - dev-3
      - deploy
  pull_request:
    branches:
      - master
      - dev
      - dev-3
env:
  environment: Development

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fill env file
        run: |
          echo "${{ secrets[format('{0}_env_file', env.environment)]}}" > .env

      - name: Import environment variables from a env file 
        uses: falti/dotenv-action@v1.1
        with:
          export-variables: true
          mask-variables: true

      - name: Build Docker Compose services
        run: |
          docker compose build

      - name: Restore dependencies
        run: dotnet restore
        shell: bash

      - name: Run unit tests
        run: dotnet test --no-restore --filter BookToAudio.UnitTests

      - name: Run integration tests #todo run with real api on master
        run: dotnet test --no-restore --filter BookToAudio.IntegrationTests

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium tests
        run: dotnet test --no-restore --filter BookToAudio.SeleniumTests
        # lala