name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  environment: staging

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NET
        uses: ./.github/actions/dotnet
      - name: Run unit tests
        run: dotnet test --no-restore --filter BookToAudio.UnitTests

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NET
        uses: ./.github/actions/dotnet
      - name: Fill env file
        run: |
          echo "${{ secrets[format('{0}_env_file', env.environment)]}}" > .env
      - name: Run integration tests
        run: dotnet test --no-restore --filter BookToAudio.IntegrationTests

  selenium-tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4
      - name: Setup NET
        uses: ./.github/actions/dotnet
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: BookToAudio.Web/package-lock.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: |
          cd BookToAudio.Web
          npm ci
      - name: Fill env file
        run: |
          echo "${{ secrets[format('{0}_env_file', env.environment)]}}" > .env
      - name: Run Selenium tests
        run: dotnet test --no-restore --filter BookToAudio.SeleniumTests
