name: Run tests
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Tmp build
      run: |
        dotnet build BookToAudio.Core
        dotnet build BookToAudio.Realtime
        dotnet build BookToAudio.Web
        dotnet build BookToAudio.SeleniumTests
        dotnet build BookToAudio.Infra
        dotnet build BookToAudio.TestingInfra
        dotnet build BookToAudio.Api
        dotnet build BookToAudio.IntegrationTests
        dotnet build BookToAudio.UnitTests

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --no-restore --verbosity normal