name: Tests Execution

permissions:
  contents: read
  packages: read
  id-token: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  environment: Development

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        test_type: [ Selenium, Unit, Integration ]

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file for tests
        env:
          github_ref: ${{ github.head_ref || github.ref_name }}
          POSTGRES_PASSWORD: devpassword
        run: |
          normalized_ref=$(echo "${github_ref}" | sed 's/\//-/g')
          IMAGE_TAG_VERSION="test-${normalized_ref}"
          echo "IMAGE_TAG_VERSION=$IMAGE_TAG_VERSION" >> .env

          CERTS_PATH=/home/runner/work
          echo "DUMMY PRIVATE KEY" >> $CERTS_PATH/privkey.pem
          echo "DUMMY FULLCHAIN CERT" >> $CERTS_PATH/fullchain.pem
          echo "CERTS_PATH=$CERTS_PATH" >> .env

          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "ConnectionStrings__DefaultConnection=User ID=dev;Password=$POSTGRES_PASSWORD;Host=db;Port=5432;Database=tts;Pooling=true;Include Error Detail=true;" >> .env
          echo "ConnectionStrings__Redis=redis:6379,allowAdmin=true" >> .env
          echo "JwtConfig__Issuer=https://localhost:7057" >> .env
          echo "JwtConfig__Audience=https://localhost:7057" >> .env
          echo "JwtConfig__ExpirationMinutes=5" >> .env
          echo "JwtConfig__Symmetric__Key=this_is_a_test_key_1234567890" >> .env
          echo "EMAILCONFIG__EMAILFROM=${{ secrets.EMAILCONFIG__EMAILFROM }}" >> .env
          echo "EMAILCONFIG__EMAILFROMPASSWORD=${{ secrets.EMAILCONFIG__EMAILFROMPASSWORD }}" >> .env
          echo "EMAILCONFIG__EMAILTO=${{ secrets.EMAILCONFIG__EMAILTO }}" >> .env
          echo "OPENAI_API_KEY=test_api_key" >> .env
          echo "ASPNETCORE_ENVIRONMENT=${{ env.environment }}" >> .env
          echo "ANGULAR_PORT=4000" >> .env
          echo "NarakeetConfig__ApiUrl=https://mock.api" >> .env
          echo "NarakeetConfig__ApiKey=test_api_key" >> .env
          echo "IsTestMode=true" >> .env

      - name: Export environment variables from an env file 
        uses: falti/dotenv-action@v1.1
        with:
          export-variables: true
          keys-case: bypass
          log-variables: true

      - name: Generate test SSL certs
        if: matrix.test_type == 'Selenium'
        run: |
          openssl req -x509 -nodes -days 1 -newkey rsa:1024 \
            -subj "/CN=localhost" \
            -keyout $CERTS_PATH/privkey.pem \
            -out $CERTS_PATH/fullchain.pem

      - name: Log in to Docker Hub
        if: matrix.test_type == 'Selenium'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and start containers for tests
        if: matrix.test_type == 'Selenium'
        run: |
          export DOCKER_BUILDKIT=1
          docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
          docker compose push
          docker network create elk
          docker compose up -d || true

      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --no-restore --filter TextToSpeech.${{ matrix.test_type }}Tests

      - name: Show logs api (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker logs api || true

      - name: Show inspect api (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker inspect api || true     

      - name: Show logs web (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker logs web || true

      - name: Show logs db (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker logs db || true

      - name: Show docker inspect db (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker inspect db

      # - name: Show logs (if Selenium tests failed)
      #   if: matrix.test_type == 'Selenium' && failure()
      #   run: |
      #     docker logs api || true
      #     docker logs web || true
      #     docker logs db || true
      #     docker logs redis || true