name: Run tests
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: dotnet build

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-build --no-restore --verbosity normal