name: CI

on:
  push:
    branches:
      - master
      - dev
      - tests-2
  pull_request:
    branches:
      - master
      - dev

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.sln') }}
          cache-restore-keys: |
            ${{ runner.os }}-dotnet-
      - name: Restore dependencies
        run: dotnet restore
      - name: Run unit tests
        run: dotnet test --no-restore --filter TestCategory=Unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.sln') }}
          cache-restore-keys: |
            ${{ runner.os }}-dotnet-
      - name: Restore dependencies
        run: dotnet restore
      - name: Run integration tests
        run: dotnet test --no-restore --filter TestCategory=Integration

  selenium-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Build and serve Angular app
        run: |
          cd BookToAudio.Web
          npm install
          npm run build
          npm start &
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.sln') }}
          cache-restore-keys: |
            ${{ runner.os }}-dotnet-
      - name: Run Selenium tests
        run: dotnet test --filter TestCategory=Selenium
