name: Tests Execution

permissions:
  contents: read
  packages: read
  id-token: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  environment: Development
  certs-path: /home/runner/work/TextToSpeech/TextToSpeech/TextToSpeech.Web/nginx/certs

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        test_type: [ Selenium, Unit, Integration ]

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file for tests
        run: |
          cat << EOF > .env
          ConnectionStrings__DefaultConnection=User ID=dev;Password=devpassword;Host=db;Port=5432;Database=tts;Pooling=true;Include Error Detail=true;
          ConnectionStrings__Redis=redis:6379,allowAdmin=true
          JwtConfig__Issuer=https://localhost:7057
          JwtConfig__Audience=https://localhost:7057
          JwtConfig__ExpirationMinutes=5
          JwtConfig__Symmetric__Key=###
          EMAILCONFIG__EMAILFROM=${{ secrets.EMAILCONFIG__EMAILFROM }}
          EMAILCONFIG__EMAILFROMPASSWORD=${{ secrets.EMAILCONFIG__EMAILFROMPASSWORD }}
          EMAILCONFIG__EMAILTO=${{ secrets.EMAILCONFIG__EMAILTO }}
          OPENAI_API_KEY=###
          ASPNETCORE_ENVIRONMENT=${{ env.environment }}
          ANGULAR_PORT=4000
          NarakeetConfig__ApiUrl=https://mock.api
          NarakeetConfig__ApiKey=###
          POSTGRES_PASSWORD=devpassword
          IsTestMode=true
          EOF

      - name: Export environment variables from an env file 
        uses: falti/dotenv-action@v1.1
        with:
          export-variables: true
          mask-variables: true  

      - name: Log in to Docker Hub
        if: matrix.test_type == 'Selenium'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start containers for tests
        if: matrix.test_type == 'Selenium'
        run: |
          export DOCKER_BUILDKIT=1
          docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
          docker compose push
          docker network create elk
          docker compose up -d

      - name: Cache NuGet Packages #test
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --no-restore --filter TextToSpeech.${{ matrix.test_type }}Tests

      - name: Show logs (if Selenium tests failed)
        if: matrix.test_type == 'Selenium' && failure()
        run: |
          docker logs api || true
          docker logs web || true