name: Run tests
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal