name: CI

on:
  push:
    branches:
      - master
      - dev
      - dev-3
      - deploy
  pull_request:
    branches:
      - master
      - dev
      - dev-3
env:
  environment: Development

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Echo env file secret name
        run: echo ${{ format('{0}_env_file', env.environment) }}

      - name: Fill env file
        run: |
          echo "${{ secrets[format('{0}_env_file', env.environment)]}}" > .env

      - name: Build Docker Compose services
        run: |
          docker compose build

      - name: Run unit tests
        run: dotnet test --no-restore --filter BookToAudio.UnitTests

      - name: Run integration tests #todo run with real api on master
        run: dotnet test --no-restore --filter BookToAudio.IntegrationTests

      - name: Start Docker Compose services
        run: docker compose up -d
        # run: ANGULAR_PORT=4000 ENVIRONMENT=${{ env.environment }} docker compose up -d

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Selenium tests
        run: dotnet test --no-restore --filter BookToAudio.SeleniumTests